import { v4 as uuid } from "uuid";
import { IPlayers } from "./types";

export const initialState: IPlayers = {
  players: {
    randi: {
      id: `randi`,
      key: uuid(),
      userName: "Randolph Gordon",
      email: "someEmail@email.com",
      height: "183cm",
      team: "team-2",
      league: "srijeda-nogomet",
      isInEditMode: false,
    },
    vedran: {
      id: `vedran`,
      key: uuid(),
      userName: "Vedran",
      email: "someEmail@email.com",
      height: "173cm",
      team: "team-2",
      league: "srijeda-nogomet",
      isInEditMode: false,
    },
    marija: {
      id: `marija`,
      key: uuid(),
      userName: "Marija Biscan",
      email: "someEmail@email.com",
      height: "173cm",
      team: "team-2",
      league: "srijeda-nogomet",
      isInEditMode: false,
    },
    teslim: {
      id: `teslim`,
      key: uuid(),
      userName: "Teslim Shitoo",
      email: "someEmail@email.com",
      height: "163cm",
      team: "team-2",
      league: "srijeda-nogomet",
      isInEditMode: false,
    },
    darko: {
      id: `darko`,
      key: uuid(),
      userName: "Darko",
      email: "someEmail@email.com",
      height: "180cm",
      team: "team-2",
      league: "srijeda-nogomet",
      isInEditMode: false,
    },
    sokre: {
      id: `sokre`,
      key: uuid(),
      userName: "Sokre",
      email: "someEmail@email.com",
      height: "153cm",
      team: "team-2",
      league: "srijeda-nogomet",
      isInEditMode: false,
    },
    kreso: {
      id: `kreso`,
      key: uuid(),
      userName: "Kreso",
      email: "someEmail@email.com",
      height: "151cm",
      team: "team-2",
      league: "srijeda-nogomet",
      isInEditMode: false,
    },
    dominick: {
      id: `dominick`,
      key: uuid(),
      userName: "Dominick",
      email: "someEmail@email.com",
      height: "166cm",
      team: "team-2",
      league: "srijeda-nogomet",
      isInEditMode: false,
    },
    filip: {
      id: `filip`,
      key: uuid(),
      userName: "Filip",
      email: "someEmail@email.com",
      height: "176cm",
      team: "team-2",
      league: "srijeda-nogomet",
      isInEditMode: false,
    },
    pavao: {
      id: `pavao`,
      key: uuid(),
      userName: "Pavao",
      email: "someEmail@email.com",
      height: "199cm",
      team: "team-2",
      league: "srijeda-nogomet",
      isInEditMode: false,
    },
    rido: {
      id: `rido`,
      key: uuid(),
      userName: "Rido",
      email: "someEmail@email.com",
      height: "169cm",
      team: "team-2",
      league: "srijeda-nogomet",
      isInEditMode: false,
    },
    chris: {
      id: `chris`,
      key: uuid(),
      userName: "Chris",
      email: "someEmail@email.com",
      height: "184cm",
      team: "team-2",
      league: "srijeda-nogomet",
      isInEditMode: false,
    },
  },
  tempInfo: {},
};
